### ISSUE TITLE
Add AWS aspects

### ISSUE THREAD

**Issue by johnsonr** [atomist/org-visualizer#2]
Many things in AWS projects would seem a good fit for aspects that could expose information, drift and help drive for consistency where appropriate. For example, consider the following file format:

```
Type: AWS::Lambda::Function
Properties: 
  Code: 
    Code
  DeadLetterConfig: 
    DeadLetterConfig
  Description: String
  Environment: 
    Environment
  FunctionName: String
  Handler: String
  KmsKeyArn: String
  Layers: 
    - String
  MemorySize: Integer
  ReservedConcurrentExecutions: Integer
  Role: String
  Runtime: String
  Tags: 
    - Tag
  Timeout: Integer
  TracingConfig: 
    TracingConfig
  VpcConfig: 
    VpcConfig
```

Possibilities include:

- Detecting individual Lambda functions
- Detecting Lambda runtimes
- Detecting security config
- Detecting concurrency config
